### ISSUE TITLE
Allow the LoRa chip to share the SPI bus

### ISSUE THREAD

**Issue by ceekdee** [ceekdee/lora#31]
Issue https://github.com/embassy-rs/lora-phy/issues/30 has identified a use case where it would be beneficial for the SPI interface to the LoRa chip to share the SPI bus.

**Comment by lulf** [comment]
One way to accomplish this is to move to the SpiDevice traits from embedded-hal and embedded-hal-async: https://docs.rs/embedded-hal/1.0.0-rc.1/embedded_hal/spi/trait.SpiDevice.html

This trait is implemented in https://github.com/embassy-rs/embassy/blob/main/examples/rp/src/bin/spi_display.rs#L61-L65
